INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (1, 'Atlanta Reign', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (2, 'Boston Uprising', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (3, 'Chengdu Hunters', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (4, 'Dallas Fuel', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (5, 'Florida Mayhem', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (6, 'Guangzhou Charge', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (7, 'Hangzhou Spark', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (8, 'Houston Outlaws', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (9, 'London Spitfire', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (10, 'Los Angeles Gladiators', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (11, 'Los Angeles Valiant', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (12, 'New York Excelsior', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (13, 'Paris Eternal', 'Vegas Eternal');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (14, 'Philadelphia Fusion', 'Seoul Infernal');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (15, 'San Francisco Shock', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (16, 'Seoul Dynasty', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (17, 'Shanghai Dragons', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (18, 'Toronto Defiant', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (19, 'Vancouver Titans', 'NULL');
INSERT INTO owlproject.teams_table (team_id, team_name, rebrand_name) VALUES (20, 'Washington Justice', 'NULL');
